# Markdown linting rules configuration
default: true

# MD013 - Line length
MD013: false

# MD024 - Multiple headers with same content
MD024: false

# MD033 - Inline HTML
MD033: false

# MD041 - First line in file should be h1 header
MD041: false

# MD029 - Ordered list item prefix
MD029: false

# MD031 - Fenced code blocks should be surrounded by blank lines
MD031: false

# MD032 - Lists should be surrounded by blank lines
MD032: false

# MD040 - Fenced code blocks should have a language specified
MD040: false

# MD022 - Headers should be surrounded by blank lines
MD022: false
