name: 'Configure AWS'
description: 'Configures AWS credentials, authenticates to ECR, and creates AWS profile'

inputs:
  aws-access-key:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: 'eu-west-1'
  eks-cluster:
    description: 'EKS cluster name'
    required: false

outputs:
  registry_url:
    description: 'The URL of the ECR registry'
    value: ${{ steps.get-registry-url.outputs.registry_url }}

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Get ECR registry URL
      id: get-registry-url
      shell: bash
      run: |
        account_id=$(aws sts get-caller-identity --query Account --output text)
        registry_url="${account_id}.dkr.ecr.${inputs.aws-region}.amazonaws.com"
        echo "registry_url=${registry_url}" >> $GITHUB_OUTPUT

    - name: Login to Amazon ECR
      shell: bash
      run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | \
        docker login --username AWS --password-stdin ${{ steps.get-registry-url.outputs.registry_url }}

    - name: Configure kubectl for EKS
      if: inputs.eks-cluster != ''
      shell: bash
      run: |
        aws eks update-kubeconfig \
          --region ${{ inputs.aws-region }} \
          --name ${{ inputs.eks-cluster }}
